spring:
  application:
    name: tour-package-2306165540-be

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  profiles:
    active: "dev"

  jpa:
    hibernate:
      ddl-auto: update

security:
  jwt:
    jwtSecret: "${JWT_SECRET_KEY}"
    jwtExpirationMs: 86400000

bill:
  service:
    base-url: "${BILL_SERVICE_BASE_URL:http://2306240124-be.hafizmuh.site}"
    api-key: "${BILL_SERVICE_API_KEY:puA0lv08ct8OmntTlBkiGuUnM5ax8BBq}"
    create-path: /api/bill/create
